export default {
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT',
  USER_REGISTER_EXISTS: 'USER_REGISTER_EXISTS',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  PAYMENT: {
    ERROR_NOT_MODIFY: 'ERROR_NOT_MODIFY',
    API_DENIED: 'API_DENIED',
    MERCHANT_NOT_VALIDATE: 'MERCHANT_NOT_VALIDATE',
    MD5_CHECK_SUM: 'MD5_CHECK_SUM',
    MERCHANT_NOT_EXISTS: 'MERCHANT_NOT_EXISTS',
    MERCHANT_IS_LOCKED: 'MERCHANT_IS_LOCKED',
    CARD_MOBILE_USED: 'CARD_MOBILE_USED',
    CARD_MOBILE_LOCKED: 'CARD_MOBILE_LOCKED',
    CARD_MOBILE_EXPIRED: 'CARD_MOBILE_EXPIRED',
    CARD_MOBILE_NOT_ACTIVE: 'CARD_MOBILE_NOT_ACTIVE',
    CARD_MOBILE_CODE_INVALID: 'CARD_MOBILE_CODE_INVALID',
    CARD_MOBILE_SERIAL_INVALID: 'CARD_MOBILE_SERIAL_INVALID',
    CARD_MOBILE_NOT_EXISTS: 'CARD_MOBILE_NOT_EXISTS',
    CARD_MOBILE_NOT_USED: 'CARD_MOBILE_NOT_USED',
    CARD_MOBILE_LIMIT: 'CARD_MOBILE_LIMIT',
    SERVER_TELCO_LIMIT: 'SERVER_TELCO_LIMIT',
    SERVER_TELCO_CONNECT_PARTNER: 'SERVER_TELCO_CONNECT_PARTNER',
    TRANSACTION_HAVE_EXISTS: 'TRANSACTION_HAVE_EXISTS_OR',
    CHECKOUT_HAVE_ERROR: 'CHECKOUT_HAVE_ERROR',
    TRANSACTION_NOT_EXISTS_OR_SUCCESSED: 'TRANSACTION_NOT_EXISTS_OR_SUCCESSED'
  }
}
